name: Deploy with devopsellence
description: Build, push, and deploy your app using devopsellence
inputs:
  token:
    description: devopsellence API token
    required: true
runs:
  using: composite
  steps:
    - name: Install devopsellence CLI
      shell: bash
      run: curl -fsSL https://devopsellence.com/lfg.sh | sh
    - name: Deploy
      shell: bash
      env:
        DEVOPSELLENCE_TOKEN: ${{ inputs.token }}
      run: devopsellence deploy --non-interactive
